// ============================================================
// KBS Staff App — Mock Data (for demo / offline development)
// ============================================================

import { User, Task, Notification } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Nguyễn Văn An',
    email: 'an.nguyen@kbs.vn',
    phone: '0901234567',
    role: 'delivery_driver',
    department: 'Vận chuyển',
    employeeCode: 'KBS-D001',
    avatarUrl: 'https://i.pinimg.com/736x/0e/71/c3/0e71c36795c37f092c6a1716b6e263a4.jpg',
  },
  {
    id: 'u2',
    name: 'Trần Thị Bích',
    email: 'bich.tran@kbs.vn',
    phone: '0912345678',
    role: 'cleaner',
    department: 'Vệ sinh',
    employeeCode: 'KBS-C001',
    avatarUrl: 'https://i.pinimg.com/736x/0e/71/c3/0e71c36795c37f092c6a1716b6e263a4.jpg',
  },
  {
    id: 'u3',
    name: 'Lê Hoàng Minh',
    email: 'minh.le@kbs.vn',
    phone: '0923456789',
    role: 'manager',
    department: 'Quản lý',
    employeeCode: 'KBS-M001',
  },
  {
    id: 'u4',
    name: 'Phạm Thị Lan',
    email: 'lan.pham@kbs.vn',
    phone: '0934567890',
    role: 'warehouse_staff',
    department: 'Kho vận',
    employeeCode: 'KBS-W001',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    taskCode: 'KBS-2025-001',
    title: 'Deliver bedding sets to children - Bé Hoa',
    description: 'Deliver a 1.2m bedding set with a pink rabbit pattern to the customer. Leave it at the door, ring the doorbell, wait 5 minutes, and if no one is there, contact them by phone.',
    type: 'delivery',
    status: 'pending',
    priority: 'high',
    assignedTo: 'u1',
    assignedToName: 'Nguyễn Văn An',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-01-15T08:00:00Z',
    dueDate: '2025-01-15',
    dueTime: '10:00',
    customer: {
      id: 'c1',
      name: 'Nguyễn Thị Hoa',
      phone: '0981234567',
      address: '123 Nguyễn Huệ, Quận 1, TP.HCM',
      note: 'Giao giờ hành chính, có bảo vệ',
    },
    products: [
      { id: 'p1', name: 'Pink Rabbit Patterned Bedding Set', type: 'bedding', quantity: 1, description: 'Size 1.2m, light pink' },
      { id: 'p2', name: 'Anti-reflux pillow for babies', type: 'Pillow', quantity: 2 },
    ],
    photos: [],
    notes: [
      { id: 'n1', content: 'Khách yêu cầu giao trước 10h sáng', createdAt: '2025-01-15T07:30:00Z', createdBy: 'u3', authorName: 'Lê Hoàng Minh' }
    ],
    checkInOut: {},
    estimatedDuration: 30,
    serviceAddress: '123 Nguyễn Huệ, Quận 1, TP.HCM',
    orderRef: 'WEB-ORD-4521',
    tags: ['urgent', 'baby'],
  },
  {
    id: 't2',
    taskCode: 'KBS-2025-002',
    title: 'Mattress + blanket washing - Gia đình Tuấn',
    description: 'Thu gom 1 nệm 1m6 và 2 bộ bedding về xưởng giặt. Đảm bảo đóng gói cẩn thận tránh bẩn thêm khi vận chuyển. Sau khi giặt xong sẽ có đơn giao trả.',
    type: 'cleaning',
    status: 'in_progress',
    priority: 'medium',
    assignedTo: 'u2',
    assignedToName: 'Trần Thị Bích',
    createdAt: '2025-01-14T14:00:00Z',
    updatedAt: '2025-01-15T09:00:00Z',
    dueDate: '2025-01-16',
    customer: {
      id: 'c2',
      name: 'Nguyễn Anh Tuấn',
      phone: '0971234567',
      address: '45 Lê Văn Việt, Quận 9, TP.HCM',
    },
    products: [
      { id: 'p3', name: 'Nệm lò xo 1m6x2m', type: 'nệm', quantity: 1 },
      { id: 'p4', name: 'Bộ bedding', type: 'bedding', quantity: 2 },
    ],
    photos: [
      { id: 'ph1', url: 'https://picsum.photos/seed/before1/400/300', type: 'before', uploadedAt: '2025-01-15T09:05:00Z', uploadedBy: 'u2' },
    ],
    notes: [],
    checkInOut: {
      checkIn: { time: '2025-01-15T09:00:00Z', address: '45 Lê Văn Việt, Quận 9, TP.HCM' }
    },
    estimatedDuration: 120,
    serviceAddress: '45 Lê Văn Việt, Quận 9, TP.HCM',
    orderRef: 'WEB-SVC-1234',
  },
  {
    id: 't3',
    taskCode: 'KBS-2025-003',
    title: 'Thu đổi chăn cũ lấy chăn mới - Khách Hương',
    description: 'Tiếp nhận bộ chăn cũ còn tốt từ khách, kiểm tra tình trạng, ghi nhận và trao đổi chiết khấu tương ứng. Khách đã chọn bộ mới trên website.',
    type: 'trade_in',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'u1',
    assignedToName: 'Nguyễn Văn An',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    dueDate: '2025-01-15',
    dueTime: '14:00',
    customer: {
      id: 'c3',
      name: 'Trần Thị Hương',
      phone: '0961234567',
      address: '78 Phan Xích Long, Quận Bình Thạnh, TP.HCM',
    },
    products: [
      { id: 'p5', name: 'Bộ bedding cũ (thu về)', type: 'bedding cũ', quantity: 1, description: 'Cần kiểm tra tình trạng' },
      { id: 'p6', name: 'Bộ bedding mới Bamboo Premium', type: 'bedding mới', quantity: 1 },
    ],
    photos: [],
    notes: [],
    checkInOut: {},
    estimatedDuration: 45,
    serviceAddress: '78 Phan Xích Long, Quận Bình Thạnh, TP.HCM',
    orderRef: 'WEB-EX-0789',
  },
  {
    id: 't4',
    taskCode: 'KBS-2025-004',
    title: 'Nhập kho: Bộ bedding Summer 2025',
    description: 'Nhận hàng từ nhà cung cấp Minh Phát. Kiểm tra số lượng, chất lượng, nhập hệ thống kho. Báo cáo nếu có hàng lỗi.',
    type: 'warehouse_inbound',
    status: 'pending',
    priority: 'low',
    assignedTo: 'u4',
    assignedToName: 'Phạm Thị Lan',
    createdAt: '2025-01-15T07:00:00Z',
    updatedAt: '2025-01-15T07:00:00Z',
    dueDate: '2025-01-15',
    dueTime: '08:30',
    customer: {
      id: 'c4',
      name: 'NCC Minh Phát',
      phone: '02838123456',
      address: 'Kho KBS, 15 Đường số 5, KCN Tân Bình',
    },
    products: [
      { id: 'p7', name: 'Chăn hè Summer Breeze (assorted)', type: 'chăn', quantity: 50 },
      { id: 'p8', name: 'Pillow bông cao su trẻ em', type: 'Pillow', quantity: 100 },
    ],
    photos: [],
    notes: [],
    checkInOut: {},
    estimatedDuration: 60,
    orderRef: 'PO-2025-031',
  },
  {
    id: 't5',
    taskCode: 'KBS-2025-005',
    title: 'Đơn đặt may riêng - Bé Khang',
    description: 'Sản xuất bộ bedding theo yêu cầu riêng: vải lụa cao cấp, màu xanh bơ sữa, thêu tên "Bé Khang" ở góc Pillow. Size theo yêu cầu đặc biệt (1m x 1m5).',
    type: 'custom_order',
    status: 'completed',
    priority: 'high',
    assignedTo: 'u2',
    assignedToName: 'Trần Thị Bích',
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2025-01-15T11:00:00Z',
    dueDate: '2025-01-15',
    customer: {
      id: 'c5',
      name: 'Phan Thị Mai',
      phone: '0951234567',
      address: '22 Nguyễn Thị Minh Khai, Quận 3, TP.HCM',
    },
    products: [
      { id: 'p9', name: 'Bộ bedding may riêng - Bé Khang', type: 'custom', quantity: 1, description: 'Lụa cao cấp, thêu tên' },
    ],
    photos: [
      { id: 'ph2', url: 'https://picsum.photos/seed/before2/400/300', type: 'before', uploadedAt: '2025-01-10T14:00:00Z', uploadedBy: 'u2' },
      { id: 'ph3', url: 'https://picsum.photos/seed/after2/400/300', type: 'after', uploadedAt: '2025-01-15T10:55:00Z', uploadedBy: 'u2' },
    ],
    notes: [
      { id: 'n2', content: 'Đã hoàn thành sản phẩm, đẹp như mong đợi. Khách đã xác nhận hài lòng.', createdAt: '2025-01-15T11:00:00Z', createdBy: 'u2', authorName: 'Trần Thị Bích' }
    ],
    checkInOut: {
      checkIn: { time: '2025-01-10T10:15:00Z' },
      checkOut: { time: '2025-01-15T11:05:00Z' },
    },
    estimatedDuration: 300,
    orderRef: 'WEB-CUS-0055',
    tags: ['vip', 'custom'],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'nf1',
    type: 'new_task',
    title: 'Nhiệm vụ mới được giao',
    body: 'Bạn có đơn giao hàng mới: KBS-2025-001 - Giao bộ bedding trẻ em.',
    taskId: 't1',
    isRead: false,
    createdAt: '2025-01-15T08:01:00Z',
  },
  {
    id: 'nf2',
    type: 'reminder',
    title: 'Nhắc nhở: Sắp đến giờ thực hiện',
    body: 'Nhiệm vụ KBS-2025-001 dự kiến lúc 10:00. Còn 30 phút nữa.',
    taskId: 't1',
    isRead: false,
    createdAt: '2025-01-15T09:30:00Z',
  },
  {
    id: 'nf3',
    type: 'task_updated',
    title: 'Cập nhật nhiệm vụ',
    body: 'Nhiệm vụ KBS-2025-002 đã được cập nhật thêm ghi chú mới từ quản lý.',
    taskId: 't2',
    isRead: true,
    createdAt: '2025-01-14T16:00:00Z',
  },
  {
    id: 'nf4',
    type: 'system',
    title: 'Hệ thống KBS',
    body: 'Chào mừng bạn đến với ứng dụng KBS Staff! Hãy cập nhật hồ sơ cá nhân của bạn.',
    isRead: true,
    createdAt: '2025-01-13T09:00:00Z',
  },
];

// Mock credentials for demo login
export const DEMO_CREDENTIALS: Record<string, { password: string; userId: string }> = {
  'an.nguyen@kbs.vn':   { password: 'demo123', userId: 'u1' },
  'bich.tran@kbs.vn':   { password: 'demo123', userId: 'u2' },
  'minh.le@kbs.vn':     { password: 'demo123', userId: 'u3' },
  'lan.pham@kbs.vn':    { password: 'demo123', userId: 'u4' },
};
